INSERT INTO BOOK(ID,
                 AUTHOR,
                 TITLE,
                 DESCRIPTION,
                 GENRE,
                 ISBN10,
                 ISBN13,
                 PRICE)
VALUES (1,
        'J. K. Rowling',
        'Harry Potter 1 and the Philosopher''s Stone',
        'Harry Potter book',
        'FANTASY',
        '9781408855652',
        '978-1408855652',
        38.00),
       (2,
        'J. K. Rowling',
        'Harry Potter 2 and the Chamber of Secrets',
        'Harry Potter book',
        'FANTASY',
        '1408855666',
        '978-1408855904',
        41.00);

INSERT INTO CUSTOMER(ID,
                     EMAIL,
                     PASSWORD,
                     BALANCE,
                     NAME)
VALUES (1,
        'example_email',
        '$2a$12$AS0rJfGTQdJ0lY9gNb1vS.yoeKJiq.8u2ztUBlKLghop1A05UII6i',
        200,
        'example_customer'),
       (2,
        'example_email1',
        '$2a$12$xmMP83b4cA8UFxzJaQrLoOEo3cMhswO2D1dFAHkGoCVPJJ.fLeySW',
        100,
        'example_customer1')
