/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.0.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.endriu.bookstore.api;

import com.endriu.bookstore.model.BookModel;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-10-23T20:38:24.048672300+02:00[Europe/Warsaw]")
@Validated
@Tag(name = "bookservice", description = "Operations regarding books")
public interface BookserviceApi {

    /**
     * GET /bookservice/books : Returns the list of all books
     *
     * @return List of all books (status code 200)
     */
    @Operation(
        operationId = "bookserviceBooksGet",
        summary = "Returns the list of all books",
        tags = { "books" },
        responses = {
            @ApiResponse(responseCode = "200", description = "List of all books", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = BookModel.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/bookservice/books",
        produces = { "application/json" }
    )
    ResponseEntity<List<BookModel>> bookserviceBooksGet(
        
    );

}
